---
title: "edge_events_d_0"
author: "Tong"
date: "11/18/2021"
output: html_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r step 1 and step 2}
#### step 1, build PT+N rank equations in the R environment

#### step 2, construct the probability space
nsim <- 1e4
A <- rbeta(nsim, 1, 10)
not_A = 1-A
B <- rbeta(nsim, 1, 10)
not_B = 1 - B

event_set <- cbind(A, not_A, B, not_B) %>% as.matrix()


```

```{r step 3, 4 and 5}
#### step 3 
# Functions to implement PT+N rank equations for each row in the probabilty space

get_diff_rates <- function(n, a, na, b, nb) {
  
  r1 <- pr_linear(n, a, b, nb, na) # no error
  r2 <- pr_linear(n, a, b, na, nb) # type2
  r3 <- pr_linear(n, a, nb, b, na) #no error
  r4 <- pr_linear(n, a, nb, na, b) #type2
  
  r5 <- pr_linear(n, a, na, b, nb) #type 1
  r6 <- pr_linear(n, a, na, nb, b) #type 1
  
  r7 <- pr_linear(n, b, a, nb, na) #type 2
  r8 <- pr_linear(n, b, a, na, nb) # no error
  
  r9 <- pr_linear(n, b, nb, a, na) # type 1
  r10 <- pr_linear(n, b, nb, na, a) #type 1
  
  r11 <- pr_linear(n, b, na, a, nb) #no error
  r12 <- pr_linear(n, b, na, nb, a) #type 2
  r13 <- pr_linear(n, nb, a, b, na) #type2
  r14 <- pr_linear(n, nb, a, na, b) #no error
  
  r15 <- pr_linear(n, nb, b, a, na) #type 1
  r16 <- pr_linear(n, nb, b, na, a) #type 1
  
  r17 <- pr_linear(n, nb, na, a, b) #no error
  r18 <- pr_linear(n, nb, na, b, a) #type 2
  
  r19 <- pr_linear(n, na, a, b, nb) #type 1
  r20 <- pr_linear(n, na, a, nb, b) #type 1
  
  r21 <- pr_linear(n, na, b, a, nb) #type 2
  r22 <- pr_linear(n, na, b, nb, a) #no error
  r23 <- pr_linear(n, na, nb, a, b) #type 2
  r24 <- pr_linear(n, na, nb, b, a) #no error
  
  # use three fields and the relationship is like A=B > C > D
  h1 <- pr_one_pair_case_1(n, a, na, b, nb) #type1
  h2 <- pr_one_pair_case_1(n, a, na, nb, b) #type1
  
  h3 <- pr_one_pair_case_1(n, a, b, na, nb) #type2
  h4 <- pr_one_pair_case_1(n, a, b, nb, na) #type2
  
  h5 <- pr_one_pair_case_1(n, a, nb, na, b) #type2
  h6 <- pr_one_pair_case_1(n, a, nb, b, na) #type2
  
  h7 <- pr_one_pair_case_1(n, na, b, a, nb) #type2
  h8 <- pr_one_pair_case_1(n, na, b, nb, a) #type2
  
  h9 <- pr_one_pair_case_1(n, na, nb, a, b) #type2
  h10 <- pr_one_pair_case_1(n, na, nb, b, a) #type2
  
  h11 <- pr_one_pair_case_1(n, b, nb, a, na) #type1
  h12 <- pr_one_pair_case_1(n, b, nb, na, a) #type1
  
  # use three fields and the relationship is like A > B = C > D
  h13 <- pr_one_pair_case_2(n, a, b, nb, na) #no error
  h14 <- pr_one_pair_case_2(n, na, b, nb, a) #no error
  
  h15 <- pr_one_pair_case_2(n, a, b, na, nb) #type3
  h16 <- pr_one_pair_case_2(n, nb, b, na, a) #type3
  
  
  h19 <- pr_one_pair_case_2(n, na, b, a, nb) #type3
  h20 <- pr_one_pair_case_2(n, nb, b, a, na) #type3
  
  h21 <- pr_one_pair_case_2(n, na, nb, a, b) #type3
  h22 <- pr_one_pair_case_2(n, b, nb, a, na) #type3
  
  h17 <- pr_one_pair_case_2(n, a, nb, na, b) #type3
  h18 <- pr_one_pair_case_2(n, b, nb, na, a) #type3
  
  h23 <- pr_one_pair_case_2(n, b, na, a, nb) #no error
  h24 <- pr_one_pair_case_2(n, nb, a, na, b) #no error
  
  # use three fields and the relationship is like A > B > C = D
  
  h25 <- pr_one_pair_case_3(n, a, na, b, nb) #type1
  h26 <- pr_one_pair_case_3(n, na, a, b, nb) #type1
  
  h27 <- pr_one_pair_case_3(n, a, b, na, nb) #type2
  h28 <- pr_one_pair_case_3(n, b, a, na, nb) #type2
  
  h29 <- pr_one_pair_case_3(n, a, nb, na, b) #type2
  h30<- pr_one_pair_case_3(n, nb, a, na, b) #type2
  
  h31 <- pr_one_pair_case_3(n, na, b, a, nb) #type2
  h32 <- pr_one_pair_case_3(n, b, na, a, nb) #type2
  
  h33 <- pr_one_pair_case_3(n, na, nb, a, b) #type2
  h34 <- pr_one_pair_case_3(n, nb, na, a, b) #type2
  
  h35 <- pr_one_pair_case_3(n, b, nb, a, na) #type1
  h36 <- pr_one_pair_case_3(n, nb, b, a, na) #type1
  
  #use two fields and the relationship is like A=B=C > D
  s1 <- pr_three_tied_case1(n, a, na, b, nb) #type3
  s2 <- pr_three_tied_case1(n, a, na, nb, b) #type3
  s3 <- pr_three_tied_case1(n, a, b, nb, na) #type3
  s4 <- pr_three_tied_case1(n, na, b, nb, a) #type3
  
  #use two fields and the relationship is like A>B=C=D
  s5 <- pr_three_tied_case2(n, a, na, b, nb) #type3
  s6 <- pr_three_tied_case2(n, na, a, nb, b) #type3
  s7 <- pr_three_tied_case2(n, b, a, nb, na) #type3
  s8 <- pr_three_tied_case2(n, nb, b, na, a) #type3
  
  #use two fields and the relationship is like A>B=C>D
  t1 <- pr_two_pairs(n, a, na, b, nb) #type1
  t2 <- pr_two_pairs(n, b, nb, a, na) #type1
  
  t3 <- pr_two_pairs(n, a, b, na, nb) #no error
  t4 <- pr_two_pairs(n, a, nb, na, b) #no error
  
  t5 <- pr_two_pairs(n, na, b, a, nb) #no error
  t6 <- pr_two_pairs(n, na, nb, a, b) #no error
  
  #use only one field and the relationship is like A=B=C=D
  e1 <- pr_all_equal(n, a, na, b, nb)
  
  results <- c(r1, r2, r3, r4, r5, r6, r7, r8, r9, r10, r11, r12,
               r13, r14, r15, r16, r17, r18, r19, r20, r21, r22, r23, r24,
               h1, h2, h3, h4, h5, h6, h7, h8, h9, h10, h11, h12,
               h13, h14, h15, h16, h17, h18, h19, h20, h21, h22, h23, h24,
               h25, h26, h27, h28, h29, h30, h31, h32, h33, h34, h35, h36,
               s1, s2, s3, s4, s5, s6, s7, s8,
               t1, t2, t3, t4, t5, t6,
               e1)
  
  names(results) = c("r1", "r2", "r3", "r4", "r5", "r6", "r7", "r8", "r9", "r10", "r11", "r12",
                     "r13", "r14", "r15", "r16", "r17", "r18", "r19", "r20", "r21", "r22", "r23", "r24",
                     "h1", "h2", "h3", "h4", "h5", "h6", "h7", "h8", "h9", "h10", "h11", "h12",
                     "h13", "h14", "h15", "h16", "h17", "h18", "h19", "h20", "h21", "h22", "h23", "h24",
                     "h25", "h26", "h27", "h28", "h29", "h30", "h31", "h32", "h33", "h34", "h35", "h36",
                     "s1", "s2", "s3", "s4", "s5", "s6", "s7", "s8",
                     "t1", "t2", "t3", "t4", "t5", "t6",
                     "e1")
  return(results)
  
}

#### step 4 
## functions to vary the sample size

calcu_rates <- function(no_sample) {
  
  rates <- mapply(get_diff_rates, no_sample, event_set[, "A"], event_set[, "not_A"], event_set[, "B"], event_set[, "not_B"])
  
  return(rates)
} 

### step 5
## functions to run in multiple cores
x <- c(1:8)
events_results_1_5  <- mclapply(x, calcu_rates, mc.cores = 8)
```

```{r}
x <- c(9:16)
events_results_9_16  <- mclapply(x, calcu_rates, mc.cores = 8)
```

```{r}
x <- c(17:20)
events_results_17_20 <- mclapply(x, calcu_rates, mc.cores = 8)
```






